### ISSUE TITLE
Warning: Unreachable Code in scripts\server\map_generation.as

### ISSUE THREAD

**Issue by EngineOfDarkness** [Skeletonxf/star-ruler-2-mod-ce#3]
Upon starting Star Ruler 2 with the latest version of the Mod enabled the following Warning gets printed in the console and the `log.txt` (even before starting a new game). Not sure if just unused dead code or wip.

```
scripts\server\map_generation.as:
 Compiling void MapGeneration::generateRougeObjects()
  Warning (1140:3): Unreachable code
```

**Comment by Skeletonxf** [comment]
Yep it's intended to be dead code at the moment. Somewhat of a continual reminder to me to get deep space stuff working :)
